import { X, Download, FileText } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface MonthlyReportData {
    month: string;
    year: number;
    totalIncome: number;
    totalExpense: number;
    savingsRate: number;
    topCategories: { category: string; amount: number }[];
    transactionCount: number;
}

interface MonthlyReportModalProps {
    isOpen: boolean;
    onClose: () => void;
    data: MonthlyReportData | null;
}

export default function MonthlyReportModal({ isOpen, onClose, data }: MonthlyReportModalProps) {
    if (!isOpen || !data) return null;

    const generatePDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFillColor(22, 163, 74); // Green-600
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.text('Traxos Monthly Report', 20, 25);

        doc.setFontSize(14);
        doc.text(`${data.month} ${data.year}`, 20, 35);

        // Summary Section
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.text('Financial Summary', 20, 55);

        const summaryData = [
            ['Total Income', `INR ${data.totalIncome.toFixed(2)}`],
            ['Total Expenses', `INR ${data.totalExpense.toFixed(2)}`],
            ['Net Savings', `INR ${(data.totalIncome - data.totalExpense).toFixed(2)}`],
            ['Savings Rate', `${data.savingsRate.toFixed(1)}%`],
            ['Total Transactions', data.transactionCount.toString()]
        ];

        autoTable(doc, {
            startY: 60,
            head: [['Metric', 'Value']],
            body: summaryData,
            theme: 'striped',
            headStyles: { fillColor: [22, 163, 74] }
        });

        // Top Categories Section
        // Get the final Y position of the previous table
        const finalY = (doc as any).lastAutoTable.finalY || 120;

        doc.text('Top Spending Categories', 20, finalY + 20);

        const categoryData = data.topCategories.map(cat => [
            cat.category,
            `INR ${cat.amount.toFixed(2)}`
        ]);

        autoTable(doc, {
            startY: finalY + 25,
            head: [['Category', 'Amount']],
            body: categoryData,
            theme: 'grid',
            headStyles: { fillColor: [75, 85, 99] } // Gray-600
        });

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Traxos - Your Personal Finance Assistant', 20, 280);

        doc.save(`Traxos_Report_${data.month}_${data.year}.pdf`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl max-w-md w-full overflow-hidden border border-gray-100 dark:border-gray-700 animate-in zoom-in-95 duration-200">
                {/* Header */}
                <div className="bg-gradient-to-r from-green-600 to-green-500 p-6 text-white relative">
                    <button
                        onClick={onClose}
                        className="absolute top-4 right-4 p-2 bg-white/20 hover:bg-white/30 rounded-full transition-colors"
                    >
                        <X size={20} />
                    </button>
                    <div className="flex items-center gap-3 mb-2">
                        <FileText size={28} />
                        <h2 className="text-2xl font-bold">Monthly Report</h2>
                    </div>
                    <p className="opacity-90 font-medium">{data.month} {data.year}</p>
                </div>

                {/* Content */}
                <div className="p-6 space-y-6">
                    <div className="grid grid-cols-2 gap-4">
                        <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-xl border border-green-100 dark:border-green-900/30">
                            <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">Income</p>
                            <p className="text-lg font-bold text-green-700 dark:text-green-400">
                                ₹{data.totalIncome.toLocaleString()}
                            </p>
                        </div>
                        <div className="p-4 bg-red-50 dark:bg-red-900/20 rounded-xl border border-red-100 dark:border-red-900/30">
                            <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">Expenses</p>
                            <p className="text-lg font-bold text-red-700 dark:text-red-400">
                                ₹{data.totalExpense.toLocaleString()}
                            </p>
                        </div>
                    </div>

                    <div className="space-y-3">
                        <h3 className="font-semibold text-gray-900 dark:text-white flex items-center gap-2">
                            <span className="w-1 h-5 bg-green-500 rounded-full"></span>
                            Top Spending
                        </h3>
                        {data.topCategories.map((cat, i) => (
                            <div key={i} className="flex justify-between items-center text-sm">
                                <span className="text-gray-600 dark:text-gray-300">{cat.category}</span>
                                <span className="font-medium text-gray-900 dark:text-white">₹{cat.amount.toLocaleString()}</span>
                            </div>
                        ))}
                    </div>

                    <p className="text-xs text-center text-gray-400 dark:text-gray-500 italic">
                        "You saved {data.savingsRate.toFixed(1)}% of your income last month!"
                    </p>

                    <button
                        onClick={generatePDF}
                        className="w-full py-3 px-4 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-bold rounded-xl flex items-center justify-center gap-2 hover:opacity-90 transition-opacity shadow-lg"
                    >
                        <Download size={20} />
                        Download PDF Report
                    </button>
                </div>
            </div>
        </div>
    );
}
